enchant @p protection 4
enchant @p feather_falling 4
enchant @p respiration 3
enchant @p depth_strider 3
enchant @p aqua_affinity 1
enchant @p sharpness 5
enchant @p knockback 2
enchant @p fire_aspect 2
enchant @p efficiency 5
enchant @p silk_touch
enchant @p unbreaking 3
enchant @p power 5
enchant @p punch 2
enchant @p infinity 1
enchant @p lure 3
enchant @p riptide 3
enchant @p loyalty 3
enchant @p impaling 5
enchant @p looting 3
enchant @p mending 1
enchant @p frost_walker 2
enchant @p luck_of_the_sea 3
enchant @p multishot 1
enchant @p quick_charge 3
enchant @p swift_sneak 3