scoreboard objectives remove joined
scoreboard objectives remove coords
scoreboard objectives remove nightvision
scoreboard objectives remove vanish
scoreboard objectives remove fly
scoreboard objectives remove cam
scoreboard objectives remove tip1
scoreboard objectives remove tip2
tag @a remove host
tag @a remove admin
tag @a remove helper
tag @a remove staff
tag @a remove activecamera
tag @a remove cam1